# -*- coding: utf-8 -*-
"""db

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VtiGVNXZSpMc1QiYU-ZW_m62L7g30Wg-
"""

from sqlalchemy import create_engine, text
from sqlalchemy.engine import Engine

import os
from dotenv import load_dotenv

load_dotenv()

DB_HOST = os.getenv("DB_HOST", "localhost")
DB_PORT = int(os.getenv("DB_PORT", "5432"))
DB_NAME = os.getenv("DB_NAME", "elt_db")
DB_USER = os.getenv("DB_USER", "elt_user")
DB_PASSWORD = os.getenv("DB_PASSWORD", "elt_password")

CSV_PATH = os.getenv("CSV_PATH", "/data/raw/telecom_churn.csv")

SCHEDULE_MINUTES = int(os.getenv("SCHEDULE_MINUTES", "60"))

SQLALCHEMY_ECHO = os.getenv("SQLALCHEMY_ECHO", "false").lower() == "true"

def get_engine() -> Engine:
    url = (
        f"postgresql+psycopg2://{DB_USER}:{DB_PASSWORD}"
        f"@{DB_HOST}:{DB_PORT}/{DB_NAME}"
    )
    return create_engine(url, future=True)

def execute_sql(sql: str, **params):
    engine = get_engine()
    with engine.begin() as conn:
        conn.execute(text(sql), params)