# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15bncwA-gIHNoD7ZaRdglHwhK8cb-OKk5
"""

import logging
import time

!pip install apscheduler

from apscheduler.schedulers.background import BackgroundScheduler

import os
from dotenv import load_dotenv

load_dotenv()

DB_HOST = os.getenv("DB_HOST", "localhost")
DB_PORT = int(os.getenv("DB_PORT", "5432"))
DB_NAME = os.getenv("DB_NAME", "elt_db")
DB_USER = os.getenv("DB_USER", "elt_user")
DB_PASSWORD = os.getenv("DB_PASSWORD", "elt_password")

CSV_PATH = os.getenv("CSV_PATH", "/data/raw/telecom_churn.csv")

SCHEDULE_MINUTES = int(os.getenv("SCHEDULE_MINUTES", "60"))

SQLALCHEMY_ECHO = os.getenv("SQLALCHEMY_ECHO", "false").lower() == "true"

from .pipeline import run_pipeline

def main():
    scheduler = BackgroundScheduler()
    scheduler.add_job(
        run_pipeline,
        "interval",
        minutes=SCHEDULE_MINUTES,
        id="telecom_elt_run",
        replace_existing=True,
    )
    logger.info(f"Starting scheduler. Interval = {SCHEDULE_MINUTES} minutes.")
    scheduler.start()

    # run once immediately on startup
    run_pipeline()

    try:
        while True:
            time.sleep(60)
    except (KeyboardInterrupt, SystemExit):
        logger.info("Shutting down scheduler...")
        scheduler.shutdown()
if __name__ == "__main__":
    main()